// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsInvalidRole(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_ROLE.String() && e.Code == 400
}

// 为某个枚举单独设置错误码
func ErrorInvalidRole(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_ROLE.String(), fmt.Sprintf(format, args...))
}

func IsEmptyContent(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_EMPTY_CONTENT.String() && e.Code == 400
}

func ErrorEmptyContent(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_EMPTY_CONTENT.String(), fmt.Sprintf(format, args...))
}

func IsNoChoice(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NO_CHOICE.String() && e.Code == 503
}

func ErrorNoChoice(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorReason_NO_CHOICE.String(), fmt.Sprintf(format, args...))
}

func IsOpenaiError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OPENAI_ERROR.String() && e.Code == 503
}

func ErrorOpenaiError(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorReason_OPENAI_ERROR.String(), fmt.Sprintf(format, args...))
}
