// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proxy/v1/openai.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenAI_StreamResponsesCompletion_FullMethodName = "/proxy.v1.OpenAI/StreamResponsesCompletion"
)

// OpenAIClient is the client API for OpenAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenAIClient interface {
	StreamResponsesCompletion(ctx context.Context, in *StreamResponsesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponsesResponse], error)
}

type openAIClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenAIClient(cc grpc.ClientConnInterface) OpenAIClient {
	return &openAIClient{cc}
}

func (c *openAIClient) StreamResponsesCompletion(ctx context.Context, in *StreamResponsesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponsesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OpenAI_ServiceDesc.Streams[0], OpenAI_StreamResponsesCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamResponsesRequest, StreamResponsesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenAI_StreamResponsesCompletionClient = grpc.ServerStreamingClient[StreamResponsesResponse]

// OpenAIServer is the server API for OpenAI service.
// All implementations must embed UnimplementedOpenAIServer
// for forward compatibility.
type OpenAIServer interface {
	StreamResponsesCompletion(*StreamResponsesRequest, grpc.ServerStreamingServer[StreamResponsesResponse]) error
	mustEmbedUnimplementedOpenAIServer()
}

// UnimplementedOpenAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenAIServer struct{}

func (UnimplementedOpenAIServer) StreamResponsesCompletion(*StreamResponsesRequest, grpc.ServerStreamingServer[StreamResponsesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamResponsesCompletion not implemented")
}
func (UnimplementedOpenAIServer) mustEmbedUnimplementedOpenAIServer() {}
func (UnimplementedOpenAIServer) testEmbeddedByValue()                {}

// UnsafeOpenAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenAIServer will
// result in compilation errors.
type UnsafeOpenAIServer interface {
	mustEmbedUnimplementedOpenAIServer()
}

func RegisterOpenAIServer(s grpc.ServiceRegistrar, srv OpenAIServer) {
	// If the following call pancis, it indicates UnimplementedOpenAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenAI_ServiceDesc, srv)
}

func _OpenAI_StreamResponsesCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamResponsesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OpenAIServer).StreamResponsesCompletion(m, &grpc.GenericServerStream[StreamResponsesRequest, StreamResponsesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenAI_StreamResponsesCompletionServer = grpc.ServerStreamingServer[StreamResponsesResponse]

// OpenAI_ServiceDesc is the grpc.ServiceDesc for OpenAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.v1.OpenAI",
	HandlerType: (*OpenAIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResponsesCompletion",
			Handler:       _OpenAI_StreamResponsesCompletion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proxy/v1/openai.proto",
}
