// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proxy/v1/perplexity.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 客户端参数错误（包含角色、内容、参数、请求格式等所有输入验证错误）
	ErrorReason_INVALID_ARGUMENT ErrorReason = 0
	// 响应中没有可用的选项
	ErrorReason_NO_CHOICE ErrorReason = 1
	// 上游 API 服务错误（如 OpenAI API 调用失败）
	ErrorReason_UPSTREAM_API_ERROR ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "INVALID_ARGUMENT",
		1: "NO_CHOICE",
		2: "UPSTREAM_API_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"INVALID_ARGUMENT":   0,
		"NO_CHOICE":          1,
		"UPSTREAM_API_ERROR": 2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proxy_v1_perplexity_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_proxy_v1_perplexity_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_proxy_v1_perplexity_proto_rawDescGZIP(), []int{0}
}

type MessageRole int32

const (
	MessageRole_CHAT_COMPLETION_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_CHAT_COMPLETION_MESSAGE_ROLE_SYSTEM      MessageRole = 1
	MessageRole_CHAT_COMPLETION_MESSAGE_ROLE_USER        MessageRole = 2
	MessageRole_CHAT_COMPLETION_MESSAGE_ROLE_ASSISTANT   MessageRole = 3
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "CHAT_COMPLETION_MESSAGE_ROLE_UNSPECIFIED",
		1: "CHAT_COMPLETION_MESSAGE_ROLE_SYSTEM",
		2: "CHAT_COMPLETION_MESSAGE_ROLE_USER",
		3: "CHAT_COMPLETION_MESSAGE_ROLE_ASSISTANT",
	}
	MessageRole_value = map[string]int32{
		"CHAT_COMPLETION_MESSAGE_ROLE_UNSPECIFIED": 0,
		"CHAT_COMPLETION_MESSAGE_ROLE_SYSTEM":      1,
		"CHAT_COMPLETION_MESSAGE_ROLE_USER":        2,
		"CHAT_COMPLETION_MESSAGE_ROLE_ASSISTANT":   3,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proxy_v1_perplexity_proto_enumTypes[1].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_api_proxy_v1_perplexity_proto_enumTypes[1]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_api_proxy_v1_perplexity_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          MessageRole            `protobuf:"varint,1,opt,name=role,proto3,enum=proxy.v1.MessageRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proxy_v1_perplexity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_v1_perplexity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proxy_v1_perplexity_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_CHAT_COMPLETION_MESSAGE_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StreamChatCompletionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Temperature   *float64               `protobuf:"fixed64,3,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float64               `protobuf:"fixed64,4,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	Messages      []*Message             `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatCompletionsRequest) Reset() {
	*x = StreamChatCompletionsRequest{}
	mi := &file_api_proxy_v1_perplexity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatCompletionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatCompletionsRequest) ProtoMessage() {}

func (x *StreamChatCompletionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_v1_perplexity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatCompletionsRequest.ProtoReflect.Descriptor instead.
func (*StreamChatCompletionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_v1_perplexity_proto_rawDescGZIP(), []int{1}
}

func (x *StreamChatCompletionsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamChatCompletionsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StreamChatCompletionsRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *StreamChatCompletionsRequest) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *StreamChatCompletionsRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type StreamChatCompletionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*StreamChatCompletionsResponse_ReasoningChunk
	//	*StreamChatCompletionsResponse_MessageChunk
	Content       isStreamChatCompletionsResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatCompletionsResponse) Reset() {
	*x = StreamChatCompletionsResponse{}
	mi := &file_api_proxy_v1_perplexity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatCompletionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatCompletionsResponse) ProtoMessage() {}

func (x *StreamChatCompletionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_v1_perplexity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatCompletionsResponse.ProtoReflect.Descriptor instead.
func (*StreamChatCompletionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proxy_v1_perplexity_proto_rawDescGZIP(), []int{2}
}

func (x *StreamChatCompletionsResponse) GetContent() isStreamChatCompletionsResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StreamChatCompletionsResponse) GetReasoningChunk() string {
	if x != nil {
		if x, ok := x.Content.(*StreamChatCompletionsResponse_ReasoningChunk); ok {
			return x.ReasoningChunk
		}
	}
	return ""
}

func (x *StreamChatCompletionsResponse) GetMessageChunk() string {
	if x != nil {
		if x, ok := x.Content.(*StreamChatCompletionsResponse_MessageChunk); ok {
			return x.MessageChunk
		}
	}
	return ""
}

type isStreamChatCompletionsResponse_Content interface {
	isStreamChatCompletionsResponse_Content()
}

type StreamChatCompletionsResponse_ReasoningChunk struct {
	ReasoningChunk string `protobuf:"bytes,1,opt,name=reasoning_chunk,json=reasoningChunk,proto3,oneof"`
}

type StreamChatCompletionsResponse_MessageChunk struct {
	MessageChunk string `protobuf:"bytes,2,opt,name=message_chunk,json=messageChunk,proto3,oneof"`
}

func (*StreamChatCompletionsResponse_ReasoningChunk) isStreamChatCompletionsResponse_Content() {}

func (*StreamChatCompletionsResponse_MessageChunk) isStreamChatCompletionsResponse_Content() {}

var File_api_proxy_v1_perplexity_proto protoreflect.FileDescriptor

const file_api_proxy_v1_perplexity_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proxy/v1/perplexity.proto\x12\bproxy.v1\x1a\x13errors/errors.proto\"N\n" +
	"\aMessage\x12)\n" +
	"\x04role\x18\x01 \x01(\x0e2\x15.proxy.v1.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xd4\x01\n" +
	"\x1cStreamChatCompletionsRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\vtemperature\x18\x03 \x01(\x01H\x00R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x04 \x01(\x01H\x01R\x04topP\x88\x01\x01\x12-\n" +
	"\bmessages\x18\x05 \x03(\v2\x11.proxy.v1.MessageR\bmessagesB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_p\"|\n" +
	"\x1dStreamChatCompletionsResponse\x12)\n" +
	"\x0freasoning_chunk\x18\x01 \x01(\tH\x00R\x0ereasoningChunk\x12%\n" +
	"\rmessage_chunk\x18\x02 \x01(\tH\x00R\fmessageChunkB\t\n" +
	"\acontent*b\n" +
	"\vErrorReason\x12\x1a\n" +
	"\x10INVALID_ARGUMENT\x10\x00\x1a\x04\xa8E\x90\x03\x12\x13\n" +
	"\tNO_CHOICE\x10\x01\x1a\x04\xa8E\xf4\x03\x12\x1c\n" +
	"\x12UPSTREAM_API_ERROR\x10\x02\x1a\x04\xa8E\xf6\x03\x1a\x04\xa0E\xf4\x03*\xb7\x01\n" +
	"\vMessageRole\x12,\n" +
	"(CHAT_COMPLETION_MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12'\n" +
	"#CHAT_COMPLETION_MESSAGE_ROLE_SYSTEM\x10\x01\x12%\n" +
	"!CHAT_COMPLETION_MESSAGE_ROLE_USER\x10\x02\x12*\n" +
	"&CHAT_COMPLETION_MESSAGE_ROLE_ASSISTANT\x10\x032z\n" +
	"\n" +
	"Perplexity\x12l\n" +
	"\x15StreamChatCompletions\x12&.proxy.v1.StreamChatCompletionsRequest\x1a'.proxy.v1.StreamChatCompletionsResponse\"\x000\x01B3Z1github.com/wolodata/proxy-service/api/proxy/v1;v1b\x06proto3"

var (
	file_api_proxy_v1_perplexity_proto_rawDescOnce sync.Once
	file_api_proxy_v1_perplexity_proto_rawDescData []byte
)

func file_api_proxy_v1_perplexity_proto_rawDescGZIP() []byte {
	file_api_proxy_v1_perplexity_proto_rawDescOnce.Do(func() {
		file_api_proxy_v1_perplexity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proxy_v1_perplexity_proto_rawDesc), len(file_api_proxy_v1_perplexity_proto_rawDesc)))
	})
	return file_api_proxy_v1_perplexity_proto_rawDescData
}

var file_api_proxy_v1_perplexity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proxy_v1_perplexity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proxy_v1_perplexity_proto_goTypes = []any{
	(ErrorReason)(0),                      // 0: proxy.v1.ErrorReason
	(MessageRole)(0),                      // 1: proxy.v1.MessageRole
	(*Message)(nil),                       // 2: proxy.v1.Message
	(*StreamChatCompletionsRequest)(nil),  // 3: proxy.v1.StreamChatCompletionsRequest
	(*StreamChatCompletionsResponse)(nil), // 4: proxy.v1.StreamChatCompletionsResponse
}
var file_api_proxy_v1_perplexity_proto_depIdxs = []int32{
	1, // 0: proxy.v1.Message.role:type_name -> proxy.v1.MessageRole
	2, // 1: proxy.v1.StreamChatCompletionsRequest.messages:type_name -> proxy.v1.Message
	3, // 2: proxy.v1.Perplexity.StreamChatCompletions:input_type -> proxy.v1.StreamChatCompletionsRequest
	4, // 3: proxy.v1.Perplexity.StreamChatCompletions:output_type -> proxy.v1.StreamChatCompletionsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proxy_v1_perplexity_proto_init() }
func file_api_proxy_v1_perplexity_proto_init() {
	if File_api_proxy_v1_perplexity_proto != nil {
		return
	}
	file_api_proxy_v1_perplexity_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proxy_v1_perplexity_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamChatCompletionsResponse_ReasoningChunk)(nil),
		(*StreamChatCompletionsResponse_MessageChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proxy_v1_perplexity_proto_rawDesc), len(file_api_proxy_v1_perplexity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proxy_v1_perplexity_proto_goTypes,
		DependencyIndexes: file_api_proxy_v1_perplexity_proto_depIdxs,
		EnumInfos:         file_api_proxy_v1_perplexity_proto_enumTypes,
		MessageInfos:      file_api_proxy_v1_perplexity_proto_msgTypes,
	}.Build()
	File_api_proxy_v1_perplexity_proto = out.File
	file_api_proxy_v1_perplexity_proto_goTypes = nil
	file_api_proxy_v1_perplexity_proto_depIdxs = nil
}
