// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proxy/v1/perplexity.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Perplexity_StreamChatCompletions_FullMethodName = "/proxy.v1.Perplexity/StreamChatCompletions"
)

// PerplexityClient is the client API for Perplexity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PerplexityClient interface {
	StreamChatCompletions(ctx context.Context, in *StreamChatCompletionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatCompletionsResponse], error)
}

type perplexityClient struct {
	cc grpc.ClientConnInterface
}

func NewPerplexityClient(cc grpc.ClientConnInterface) PerplexityClient {
	return &perplexityClient{cc}
}

func (c *perplexityClient) StreamChatCompletions(ctx context.Context, in *StreamChatCompletionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatCompletionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Perplexity_ServiceDesc.Streams[0], Perplexity_StreamChatCompletions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChatCompletionsRequest, StreamChatCompletionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Perplexity_StreamChatCompletionsClient = grpc.ServerStreamingClient[StreamChatCompletionsResponse]

// PerplexityServer is the server API for Perplexity service.
// All implementations must embed UnimplementedPerplexityServer
// for forward compatibility.
type PerplexityServer interface {
	StreamChatCompletions(*StreamChatCompletionsRequest, grpc.ServerStreamingServer[StreamChatCompletionsResponse]) error
	mustEmbedUnimplementedPerplexityServer()
}

// UnimplementedPerplexityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPerplexityServer struct{}

func (UnimplementedPerplexityServer) StreamChatCompletions(*StreamChatCompletionsRequest, grpc.ServerStreamingServer[StreamChatCompletionsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChatCompletions not implemented")
}
func (UnimplementedPerplexityServer) mustEmbedUnimplementedPerplexityServer() {}
func (UnimplementedPerplexityServer) testEmbeddedByValue()                    {}

// UnsafePerplexityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerplexityServer will
// result in compilation errors.
type UnsafePerplexityServer interface {
	mustEmbedUnimplementedPerplexityServer()
}

func RegisterPerplexityServer(s grpc.ServiceRegistrar, srv PerplexityServer) {
	// If the following call pancis, it indicates UnimplementedPerplexityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Perplexity_ServiceDesc, srv)
}

func _Perplexity_StreamChatCompletions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChatCompletionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PerplexityServer).StreamChatCompletions(m, &grpc.GenericServerStream[StreamChatCompletionsRequest, StreamChatCompletionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Perplexity_StreamChatCompletionsServer = grpc.ServerStreamingServer[StreamChatCompletionsResponse]

// Perplexity_ServiceDesc is the grpc.ServiceDesc for Perplexity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Perplexity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.v1.Perplexity",
	HandlerType: (*PerplexityServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChatCompletions",
			Handler:       _Perplexity_StreamChatCompletions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proxy/v1/perplexity.proto",
}
